# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serplot.main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 687)
        MainWindow.setMaximumSize(QtCore.QSize(767, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setEnabled(False)
        self.btn_run.setObjectName("btn_run")
        self.gridLayout.addWidget(self.btn_run, 4, 3, 1, 1)
        self.groupBoxSettings = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSettings.setEnabled(True)
        self.groupBoxSettings.setMaximumSize(QtCore.QSize(260, 16777215))
        self.groupBoxSettings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBoxSettings.setAutoFillBackground(True)
        self.groupBoxSettings.setObjectName("groupBoxSettings")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetSettings = QtWidgets.QWidget(self.groupBoxSettings)
        self.widgetSettings.setAutoFillBackground(False)
        self.widgetSettings.setObjectName("widgetSettings")
        self.formLayout = QtWidgets.QFormLayout(self.widgetSettings)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelChooseSerial = QtWidgets.QLabel(self.widgetSettings)
        self.labelChooseSerial.setObjectName("labelChooseSerial")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelChooseSerial)
        self.comboBoxChooseSerial = QtWidgets.QComboBox(self.widgetSettings)
        self.comboBoxChooseSerial.setObjectName("comboBoxChooseSerial")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxChooseSerial)
        self.labelBaudrate = QtWidgets.QLabel(self.widgetSettings)
        self.labelBaudrate.setObjectName("labelBaudrate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelBaudrate)
        self.comboBoxBaudrate = QtWidgets.QComboBox(self.widgetSettings)
        self.comboBoxBaudrate.setObjectName("comboBoxBaudrate")
        self.comboBoxBaudrate.addItem("")
        self.comboBoxBaudrate.addItem("")
        self.comboBoxBaudrate.addItem("")
        self.comboBoxBaudrate.addItem("")
        self.comboBoxBaudrate.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxBaudrate)
        self.labelNPlots = QtWidgets.QLabel(self.widgetSettings)
        self.labelNPlots.setObjectName("labelNPlots")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelNPlots)
        self.comboBoxNPlots = QtWidgets.QComboBox(self.widgetSettings)
        self.comboBoxNPlots.setMaxVisibleItems(10)
        self.comboBoxNPlots.setObjectName("comboBoxNPlots")
        self.comboBoxNPlots.addItem("")
        self.comboBoxNPlots.addItem("")
        self.comboBoxNPlots.addItem("")
        self.comboBoxNPlots.addItem("")
        self.comboBoxNPlots.addItem("")
        self.comboBoxNPlots.addItem("")
        self.comboBoxNPlots.addItem("")
        self.comboBoxNPlots.addItem("")
        self.comboBoxNPlots.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxNPlots)
        self.labelNColcumns = QtWidgets.QLabel(self.widgetSettings)
        self.labelNColcumns.setObjectName("labelNColcumns")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelNColcumns)
        self.comboBoxNColumns = QtWidgets.QComboBox(self.widgetSettings)
        self.comboBoxNColumns.setObjectName("comboBoxNColumns")
        self.comboBoxNColumns.addItem("")
        self.comboBoxNColumns.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxNColumns)
        self.labelSeparator = QtWidgets.QLabel(self.widgetSettings)
        self.labelSeparator.setObjectName("labelSeparator")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelSeparator)
        self.lineEditSeparator = QtWidgets.QLineEdit(self.widgetSettings)
        self.lineEditSeparator.setObjectName("lineEditSeparator")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditSeparator)
        self.labelTermination = QtWidgets.QLabel(self.widgetSettings)
        self.labelTermination.setObjectName("labelTermination")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelTermination)
        self.lineEditTerminator = QtWidgets.QLineEdit(self.widgetSettings)
        self.lineEditTerminator.setObjectName("lineEditTerminator")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditTerminator)
        self.labelXFactor = QtWidgets.QLabel(self.widgetSettings)
        self.labelXFactor.setObjectName("labelXFactor")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelXFactor)
        self.lineEditXFactor = QtWidgets.QLineEdit(self.widgetSettings)
        self.lineEditXFactor.setObjectName("lineEditXFactor")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEditXFactor)
        self.labelSerialDelay = QtWidgets.QLabel(self.widgetSettings)
        self.labelSerialDelay.setObjectName("labelSerialDelay")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelSerialDelay)
        self.lineEditSerialDelay = QtWidgets.QLineEdit(self.widgetSettings)
        self.lineEditSerialDelay.setObjectName("lineEditSerialDelay")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEditSerialDelay)
        self.labelUpdate = QtWidgets.QLabel(self.widgetSettings)
        self.labelUpdate.setObjectName("labelUpdate")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.labelUpdate)
        self.lineEditUpdate = QtWidgets.QLineEdit(self.widgetSettings)
        self.lineEditUpdate.setReadOnly(False)
        self.lineEditUpdate.setObjectName("lineEditUpdate")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEditUpdate)
        self.labelQueueMaxLenght = QtWidgets.QLabel(self.widgetSettings)
        self.labelQueueMaxLenght.setObjectName("labelQueueMaxLenght")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labelQueueMaxLenght)
        self.lineEditQueueMaxLenght = QtWidgets.QLineEdit(self.widgetSettings)
        self.lineEditQueueMaxLenght.setObjectName("lineEditQueueMaxLenght")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEditQueueMaxLenght)
        self.lineEditDelayQueue = QtWidgets.QLineEdit(self.widgetSettings)
        self.lineEditDelayQueue.setObjectName("lineEditDelayQueue")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEditDelayQueue)
        self.labelDelayQueue = QtWidgets.QLabel(self.widgetSettings)
        self.labelDelayQueue.setObjectName("labelDelayQueue")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelDelayQueue)
        self.verticalLayout.addWidget(self.widgetSettings)
        self.btnApply = QtWidgets.QPushButton(self.groupBoxSettings)
        self.btnApply.setEnabled(True)
        self.btnApply.setObjectName("btnApply")
        self.verticalLayout.addWidget(self.btnApply)
        self.gridLayout.addWidget(self.groupBoxSettings, 0, 0, 1, 1)
        self.groupBoxBuffers = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxBuffers.setEnabled(False)
        self.groupBoxBuffers.setMaximumSize(QtCore.QSize(260, 16777215))
        self.groupBoxBuffers.setObjectName("groupBoxBuffers")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxBuffers)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widgetSerialBuffer = QtWidgets.QWidget(self.groupBoxBuffers)
        self.widgetSerialBuffer.setObjectName("widgetSerialBuffer")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widgetSerialBuffer)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelSerialBuffer = QtWidgets.QLabel(self.widgetSerialBuffer)
        self.labelSerialBuffer.setObjectName("labelSerialBuffer")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSerialBuffer)
        self.lineEditSerialBuffer = QtWidgets.QLineEdit(self.widgetSerialBuffer)
        self.lineEditSerialBuffer.setReadOnly(True)
        self.lineEditSerialBuffer.setObjectName("lineEditSerialBuffer")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditSerialBuffer)
        self.labelStreamBuffer = QtWidgets.QLabel(self.widgetSerialBuffer)
        self.labelStreamBuffer.setObjectName("labelStreamBuffer")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelStreamBuffer)
        self.lineEditStreamBuffer = QtWidgets.QLineEdit(self.widgetSerialBuffer)
        self.lineEditStreamBuffer.setReadOnly(True)
        self.lineEditStreamBuffer.setObjectName("lineEditStreamBuffer")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditStreamBuffer)
        self.lineEditImgBuffer = QtWidgets.QLineEdit(self.widgetSerialBuffer)
        self.lineEditImgBuffer.setReadOnly(True)
        self.lineEditImgBuffer.setObjectName("lineEditImgBuffer")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditImgBuffer)
        self.labelImgBuffer = QtWidgets.QLabel(self.widgetSerialBuffer)
        self.labelImgBuffer.setObjectName("labelImgBuffer")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelImgBuffer)
        self.gridLayout_2.addWidget(self.widgetSerialBuffer, 0, 0, 1, 1)
        self.btn_clearQueue = QtWidgets.QPushButton(self.groupBoxBuffers)
        self.btn_clearQueue.setObjectName("btn_clearQueue")
        self.gridLayout_2.addWidget(self.btn_clearQueue, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxBuffers, 1, 0, 1, 1)
        self.btnSaveData = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveData.setEnabled(False)
        self.btnSaveData.setObjectName("btnSaveData")
        self.gridLayout.addWidget(self.btnSaveData, 4, 2, 1, 1)
        self.pltLayout = GraphicsLayoutWidget(self.centralwidget)
        self.pltLayout.setObjectName("pltLayout")
        self.gridLayout.addWidget(self.pltLayout, 0, 1, 4, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(MainWindow)
        self.comboBoxNPlots.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial Plotter"))
        self.btn_run.setToolTip(_translate("MainWindow", "<html><head/><body><p>press Space</p></body></html>"))
        self.btn_run.setText(_translate("MainWindow", "Run"))
        self.groupBoxSettings.setTitle(_translate("MainWindow", "Settings"))
        self.labelChooseSerial.setText(_translate("MainWindow", "Serial Port"))
        self.labelBaudrate.setText(_translate("MainWindow", "Baudrate"))
        self.comboBoxBaudrate.setCurrentText(_translate("MainWindow", "9600"))
        self.comboBoxBaudrate.setItemText(0, _translate("MainWindow", "9600"))
        self.comboBoxBaudrate.setItemText(1, _translate("MainWindow", "19200"))
        self.comboBoxBaudrate.setItemText(2, _translate("MainWindow", "38400"))
        self.comboBoxBaudrate.setItemText(3, _translate("MainWindow", "57600"))
        self.comboBoxBaudrate.setItemText(4, _translate("MainWindow", "115200"))
        self.labelNPlots.setText(_translate("MainWindow", "Number of Plots"))
        self.comboBoxNPlots.setItemText(0, _translate("MainWindow", "1"))
        self.comboBoxNPlots.setItemText(1, _translate("MainWindow", "2"))
        self.comboBoxNPlots.setItemText(2, _translate("MainWindow", "3"))
        self.comboBoxNPlots.setItemText(3, _translate("MainWindow", "4"))
        self.comboBoxNPlots.setItemText(4, _translate("MainWindow", "5"))
        self.comboBoxNPlots.setItemText(5, _translate("MainWindow", "6"))
        self.comboBoxNPlots.setItemText(6, _translate("MainWindow", "7"))
        self.comboBoxNPlots.setItemText(7, _translate("MainWindow", "8"))
        self.comboBoxNPlots.setItemText(8, _translate("MainWindow", "9"))
        self.labelNColcumns.setText(_translate("MainWindow", "Number of Colums"))
        self.comboBoxNColumns.setItemText(0, _translate("MainWindow", "1"))
        self.comboBoxNColumns.setItemText(1, _translate("MainWindow", "2"))
        self.labelSeparator.setText(_translate("MainWindow", "Separator Char"))
        self.lineEditSeparator.setText(_translate("MainWindow", ","))
        self.labelTermination.setText(_translate("MainWindow", "Termination Char"))
        self.lineEditTerminator.setText(_translate("MainWindow", "$"))
        self.labelXFactor.setText(_translate("MainWindow", "Factor X-Axis"))
        self.lineEditXFactor.setText(_translate("MainWindow", "1"))
        self.labelSerialDelay.setText(_translate("MainWindow", "Delay Serial Reading"))
        self.lineEditSerialDelay.setToolTip(_translate("MainWindow", "<html><head/><body><p>Sleep time for serial buffer reading thread in ms.</p></body></html>"))
        self.lineEditSerialDelay.setText(_translate("MainWindow", "1"))
        self.labelUpdate.setText(_translate("MainWindow", "Graph Update Interval"))
        self.lineEditUpdate.setToolTip(_translate("MainWindow", "<html><head/><body><p>Update rate for Graphs in ms.</p></body></html>"))
        self.lineEditUpdate.setText(_translate("MainWindow", "10"))
        self.labelQueueMaxLenght.setText(_translate("MainWindow", "Max Lenght Queue"))
        self.lineEditQueueMaxLenght.setText(_translate("MainWindow", "1000"))
        self.lineEditDelayQueue.setToolTip(_translate("MainWindow", "<html><head/><body><p>Sleep time for data thread in ms.</p></body></html>"))
        self.lineEditDelayQueue.setText(_translate("MainWindow", "1"))
        self.labelDelayQueue.setText(_translate("MainWindow", "Delay Data Processing"))
        self.btnApply.setText(_translate("MainWindow", "Apply Settings and Restart Plotter"))
        self.groupBoxBuffers.setTitle(_translate("MainWindow", "Buffers"))
        self.labelSerialBuffer.setText(_translate("MainWindow", "Serial Buffer"))
        self.lineEditSerialBuffer.setText(_translate("MainWindow", "0"))
        self.labelStreamBuffer.setText(_translate("MainWindow", "Stream Buffer"))
        self.lineEditStreamBuffer.setText(_translate("MainWindow", "0"))
        self.lineEditImgBuffer.setText(_translate("MainWindow", "0"))
        self.labelImgBuffer.setText(_translate("MainWindow", "IMG Queue"))
        self.btn_clearQueue.setText(_translate("MainWindow", "Flush Queue"))
        self.btnSaveData.setText(_translate("MainWindow", "Save Data"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+S"))

from pyqtgraph import GraphicsLayoutWidget
